include <cstdint> wherever missing
Fixes errors like this that are seen while building Ceph repo's main
branch on Fedora 46, 43 and 44 -

repos/ceph/src/rocksdb/include/rocksdb/trace_record.h:55:32: error: expected ‘)’ before ‘timestamp’
   55 |   explicit TraceRecord(uint64_t timestamp);

Signed-off-by: Rishabh Dave <ridave@redhat.com>