include <cstdint> wherever missing
Fixes errors like this that are seen while building Ceph repo's main
branch on Fedora 42 -

repos/ceph/cephfs-host-errno/src/rocksdb/include/rocksdb/trace_record.h:63:11: error: ‘uint64_t’ does not name a type
   63 |   virtual uint64_t GetTimestamp() const;

Signed-off-by: Rishabh Dave <ridave@redhat.com>